### ISSUE TITLE
Mocking don't work on my Swedish computer

### ISSUE THREAD

**Issue by Anders318** [svetvasilev/transmock#10]
Hi!

I have discoverd a problem running TransMock on my computer with a Swedish version of Windows 7. I didn't get the communication to work between my integration test and the BizTalk receive location. When debuggning TransMock and stepping throug the code I discovered that the PipeAccessRights used the hard coded string "Users" to identify the windows  group to grant access for the named pipe. 

The problem is on line 432 in the file _transmock-master\Communication\TransMock.Communication.NamedPipe\StreamingNamedPipeServer.cs_: 

`new PipeAccessRule(
                        "Users",
                        PipeAccessRights.CreateNewInstance | PipeAccessRights.ReadWrite,
                        System.Security.AccessControl.AccessControlType.Allow)`

One possible solution that work for me was to create a SecurityIdentifier instead, and pass that in to the constructor of PipeAccessRule.

`IdentityReference group = new SecurityIdentifier("BU"); // Built-in Users`

Can you please solve this problem in a future relese of TransMock, so that it works with other language versions of Windows?

**Comment by svetvasilev** [comment]
Hi Anders and thanks for filing this issue! Very subtle one and i am definitely fixing this soon!
Cheers, Svet
