### ISSUE TITLE
Add ability to promote BizTalk system properties by the mock adapter

### ISSUE THREAD

**Issue by svetvasilev** [svetvasilev/transmock#2]
From real project experience there was a requirement to publish a message that has its BTS.Operation property set to a specific value which would ensure that a specific orchestration was started. 
It would be great feature to allow for a wide set of built-in BizTalk system properties, like BTS.ReceivedFileName or BTS.InterchangeID to be promoted by the mock adapter

**Comment by TonyTong502** [comment]
Hi Svet

Actually I already did some work with this idea, to create a shared pipe server (like beacon server), all context property pairs for all outgoing messages will be sent there and then immediately pulled out by a validation step (similar as receive step, it is a pipe server) along with a receive step.

It actually works fine now, but we may still need to pull the context values for nothing, this is not convenient. 

I'm thinking that we probably can use some property (similar as Encoding/PromotedProperties) to mark it context value verification required.

Does it sound good?

**Comment by svetvasilev** [comment]
Hi Tony, very glad to hear that others have also realized that such feature would be very valuable. Thank you very much for sharing your experience of solving this, very much appreciated. 
From your description I can understand that what you have done is that in a send port instance context propery bag is sent as a separate message right after the actual payload message (the mesasge that you are expecting from BizTalk) is sent, however to a different static endpoint that is spun up for the lifetime of the test case. In a validation step then you pull out this extra message and perform the desired validation. One question here - how do you correlate the received context property bag with the corresponding message? This is especially vital in parallel processing scenarios where you can get some racing conditions which can result in the payload message and the corresponding property bag received in the validation step coming out of band.
I like though the idea of allowing to predefine a set of properties that you are interested in in an adapter property,
This feature here is for the other way around - inbound to BizTalk, where system properties, not only adapter ones, are promoted when a message is received through the mock adapter.
I will soon be adding a new feature for an upcoming version that would actually address exactly what you are describing. The trouble with this current feature as described is that the promotion would be static - for each and every message the same value will be promoted/written to the context over and over again. The best would be to have a per-message capability where the desired values for promotion are supplied along with the test message. The same is applicable on the way out - all/predefined set of context properties to be available along with the received message. This way there is no need to try to create complex correlation logic for message payload and its context properties - they simply will come along with the message itself.

Cheers, Svet

**Comment by TonyTong502** [comment]
Hi Svet

Thanks for the feedback.

Your understanding for what I've done is almost correct, here is my data flow, please note, I did it  for a purpose of single message context validation.

1, validation steps starts the pipe server and listening is ready
2, normal process goes, and then it reaches mock send adapter,
3, send context property bag to a shared pipe before send message (payload)
4, step 1 accepts the context bag and execute validation code

please note, in step 3, I will try to connect to server first, if connected before timeout, send bag, you will see although it works, for some cases, there is a waste.

                var connected = pipeClient.Connect(timeout);
                if (connected){ ...
                }
and in step 4, I'm using directly property name and namespace + regular expression for validation

new ContextValidationDefinition { Name = "Filename", NameSpace = "http://schemas.microsoft.com/BizTalk/2006/WindowsSharePointServices-properties", RegexPattern = "EID-[\\d]{10}-UP-DEL-EX-VAL-[\\S]{26}" }

this runs fine, however, when it goes to the parallel scenario you mentioned above, it runs into a problem I remember that the exception was pipe server is closed.

So I think, current plan I did might not good, why not just treat this bag as normal payload, and do it as required

here is the plan: 

on adapter/binding side

1, if a send port (address: url1) needs to validate context property, mark it as <Mock ContextPipeName="url1_ctx" />
2, before sending payload, check this property is null or empty, if not, send bag

on bizunit extension side, 

1, reuse receive step to pick up messages inside this pipe server: url1_ctx
2, create validation step only in association with bag value

I'm feeling this will work, what's your opinion?

Thanks
Tony

**Comment by TonyTong502** [comment]
[context.zip](https://github.com/svetvasilev/transmock/files/1386207/context.zip)

Hi Svet

I completed the code for above plan (code patch is attached)

Please run BizTalkTest.IntegrationTests.TestDynamicSendPort.TestHappyPath_TwoWay_HelperClass() 

Patch is based on BizTalk 2013 R2 and .net 4.5

**Comment by TonyTong502** [comment]
Hi Svet,

Any update for above patch? do you want to review full source code for this idea?

**Comment by svetvasilev** [comment]
Hi Tony and very sorry for not replying to your earlier. It has been very
busy last few months for me. Let me have a look at this right after new
years and will give you feedback.
Thansk and have a very Happy New Year!

Cheers, Svet

**Comment by TonyTong502** [comment]
OK, wish you a very happy new year too.

**Comment by svetvasilev** [comment]
Hi Tony, finally managed to review your changes. Looks pretty neat and is
in line with what you described of an approach for solving this.
Few comments about the implementation:
- several projects for BizTalk 2013 R2 have changed target framework from
4.5.1 to 4.5. Any particular reason for this?
- spotted one place where you defined a boolean variable with var. Though
totaly legitimate i personally stick to the premitive types being
explicitly defined, var type come very handy for complex types, especially
with long names.
- the changes to the WiX deployment definitions would no longer be
required, as this deployment approach is currently abandoned and NuGet is
the only supported way going forward.

I still think that your approach for verifying context properties is
somewhat an overkill as it requires the opening of one more pipe and
sending those over a separate channel. I still think there is a great
chance of running in some sort of racing conditions when processing things
in parallel, which your test cases are not currently verifying. You use a
single $Context pipe per mocked endpoint and in case there are 2 or more
instances of messages that are processed in parallel (lets say in de-batch
scenario) then you might end up picking the wrong message context and then
the test case would start behaving not as expected. That is why i still
believe that the approach i drafted for you, where the properties are sent
along with the message contents over the wire is far better, safer and
predictable. Then we know for sure that the context properties are indeed
the ones that belong to the given message. Thus the implementation would be
simpler, as there will be no need for additional pipes.
Furthermore, as already mentioned earlier, your implementation solves only
the propagation of properties on the way out of BizTalk. By implementing a
messaging protocol that allows for including the message properties along
with the message contents, then it will be irrelevant in which direction in
regards to BizTalk they go. It will be then possible to promote context
properties in the inbound adapter on a per message bases. A very typical
case for such behavior that i have seen used everywhere, is some logic in a
pipeline component, or orchestration, that is related to modifying the name
of a received file. This means that when working with the mock adapter we
have to force the message to appear as if it was received by the FILE
adapter. This is achieved by promoting context properties specific to the
file adapter. And this is totally legitimate to do so, but currently the
framework supports this only per end point instance, e.g. it is somewhat
static. It will give much greater flexibility if it is possible for this
promotion to be performed on a per message base, like in setting context
properties on a mock message in a test case that is about to be sent to the
integration.

Finally, I am currently working on a completely new programming model for
the framework, that has nothing to do with BizUnit. So I am planning to
incorporate this feature with the context properties in the coming changes.
Hence i see the way ahead as follows:
- if you insist to have your changes incorporated in the framework, i
suggest you create a fork and check in the changes there. This is because I
mean that your approach is off course a better and more robust solution,
and as such i cannot accept to be incorporated in the code
- if you are convinced by my reasoning and wish to abandon your
implementation, and are still interested in working with the framework,
then you can help with implementing the messaging protocol i am talking
about.

Thanks, Svet

**Comment by TonyTong502** [comment]
Hi Svet, 

Thanks for the response, 

 - Change from 4.5.1 to 4.5 is because the 4.5.1 is not installed in the working PC
 - Thanks for the tip regarding the var, actually my understanding is, var/int/Int32 is same, itis just programming sugar, if you check the IL code, you will see no difference
 - I see the Nuget package, it is good option for delivery, the change here is to make the installation correct, just ignore it if there is no future plan for it

Thanks for sharing the architecture idea to me regarding the design, 

For the parallel posting, actually it reuses existing steps for normal message, context property is a dedicated message here, the existing framework is not good for parallel messages, so it has no exception.

For the 

**if I get it right, the message protocol you mentioned, should be something like System.ServiceModel.Channels.Message, yes?**

We might just need to consider to populate context property when BizTalk receives in messages
We might just need to consider to verify context properties when BizTalk sends out messages


A few suggestion from the experience of recent usage
1, Keep it simple to use, when I try to coach my team for application, there is, indeed, heavy learning curve here.
2, If you plan a new ecosystem without BizUnit, please consider extension ability, a few other customized BizUnit steps and sub-steps created during the automated testing
3, if possible, please consider make keep Stream implementation extensible, I'm thinking NamedPipeClientStream could be replace by FileStream for technical perspective

Lastly, I will try to help implement **message protocol** you mentioned, please confirm the idea.

Thanks
Tony

**Comment by svetvasilev** [comment]
Hi Tony, thanks for your reply and for your feedback and recommendations. I
am very pleased to hear that you are coaching others to use the framework.
I will be very thankful if you would share what are the major challanges
with taking the framework into usage some other time.
One of the major reasons for me to base the usage on BizUnit is exactly to
avoid a steep learning curve.
But sleep tight - the coming changes are not meant to trash the support of
BizUnit - this part will be intact as currently everybody who use TransMock
have their tests implemented in BizUnit. So it will be very irresponsible
from me to just cut this part and say from now on you use this way instead
for writing tests with TransMock.
As for the messaging protocol your understanding is correct - it is
somthing in this direction, but with better abstraction and a way to
serialize and desirialize a message along with its BizTalk properties, and
with baked extensibility in.
You mention that the framework itself is not good in tests related to
parallel processing. Could I ask you to register any such issues in the
GitHub project, so that I can have it on the radar. I have a very limited
number of tests for such scenarios and managed to fix few issues related to
this once i enhanced those tests. Yet there are cover perhaps few percent
of most of the cases, so any specific input will help me to extend this
reach.
Will contact you when i have description and stuff for the protocol
implementation.

Thanks, Svet

**Comment by TonyTong502** [comment]
I need to recall the parallel posting issue, will do once I get detail again.

thanks for the feedback, looking forward to your solution.

**Comment by svetvasilev** [comment]
This is now implemented as part of the 1.4 release. Supports both system and custom promoted properties and works like a charm :)
