### ISSUE TITLE
TransMock BTDF extension not executed on older BTDF version

### ISSUE THREAD

**Issue by svetvasilev** [svetvasilev/transmock#4]
When trying to deploy an application to BizTalk 2013 with BTDF 5.6 the extension point defined in the TransMock.targets file is not invoked at all, even though the .target file is referenced correctly from the btdfproj file. The reason for this is the condition in the CustomDeployTarget override - it is evaluated to false because of the lack of BTDF variable BTDF_Env. Seems this one is defined first in BTDF v6.0

**Comment by Krokanis** [comment]
Hi, I just started looking at this framework and also found this issue, but also another thing with the TransMock.target file. By default it uses the TransMockHomeDir pointing to the 1.3.0 version so you also have to define the override in the BTDF Project file to point to the latest 1.3.1 version to make it to work.

**Comment by svetvasilev** [comment]
Yes adn thanks, that is very correct. Registering a separate issue on this one. Hopefully will release fixes for these very soon.
